//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIBBSNIPService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://core.nip.nibss/", ConfigurationName="NIBBSNIPService.NIPInterface")]
    public interface NIPInterface
    {
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/nameenquirysingleitemRequest", ReplyAction="http://core.nip.nibss/NIPInterface/nameenquirysingleitemResponse")]
        NIBBSNIPService.nameenquirysingleitemResponse nameenquirysingleitem(NIBBSNIPService.nameenquirysingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/nameenquirysingleitemRequest", ReplyAction="http://core.nip.nibss/NIPInterface/nameenquirysingleitemResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.nameenquirysingleitemResponse> nameenquirysingleitemAsync(NIBBSNIPService.nameenquirysingleitemRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcResponse")]
        NIBBSNIPService.fundtransfersingleitem_dcResponse fundtransfersingleitem_dc(NIBBSNIPService.fundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_dcResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(NIBBSNIPService.fundtransfersingleitem_dcRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddResponse")]
        NIBBSNIPService.fundtransfersingleitem_ddResponse fundtransfersingleitem_dd(NIBBSNIPService.fundtransfersingleitem_ddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransfersingleitem_ddResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(NIBBSNIPService.fundtransfersingleitem_ddRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemRequest", ReplyAction="http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemResponse")]
        NIBBSNIPService.txnstatusquerysingleitemResponse txnstatusquerysingleitem(NIBBSNIPService.txnstatusquerysingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemRequest", ReplyAction="http://core.nip.nibss/NIPInterface/txnstatusquerysingleitemResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.txnstatusquerysingleitemResponse> txnstatusquerysingleitemAsync(NIBBSNIPService.txnstatusquerysingleitemRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/balanceenquiryRequest", ReplyAction="http://core.nip.nibss/NIPInterface/balanceenquiryResponse")]
        NIBBSNIPService.balanceenquiryResponse balanceenquiry(NIBBSNIPService.balanceenquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/balanceenquiryRequest", ReplyAction="http://core.nip.nibss/NIPInterface/balanceenquiryResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.balanceenquiryResponse> balanceenquiryAsync(NIBBSNIPService.balanceenquiryRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/amountblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/amountblockResponse")]
        NIBBSNIPService.amountblockResponse amountblock(NIBBSNIPService.amountblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/amountblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/amountblockResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.amountblockResponse> amountblockAsync(NIBBSNIPService.amountblockRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/amountunblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/amountunblockResponse")]
        NIBBSNIPService.amountunblockResponse amountunblock(NIBBSNIPService.amountunblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/amountunblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/amountunblockResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.amountunblockResponse> amountunblockAsync(NIBBSNIPService.amountunblockRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/accountblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/accountblockResponse")]
        NIBBSNIPService.accountblockResponse accountblock(NIBBSNIPService.accountblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/accountblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/accountblockResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.accountblockResponse> accountblockAsync(NIBBSNIPService.accountblockRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/accountunblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/accountunblockResponse")]
        NIBBSNIPService.accountunblockResponse accountunblock(NIBBSNIPService.accountunblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/accountunblockRequest", ReplyAction="http://core.nip.nibss/NIPInterface/accountunblockResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.accountunblockResponse> accountunblockAsync(NIBBSNIPService.accountunblockRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/adjustNIPSettingsRequest", ReplyAction="http://core.nip.nibss/NIPInterface/adjustNIPSettingsResponse")]
        NIBBSNIPService.adjustNIPSettingsResponse adjustNIPSettings(NIBBSNIPService.adjustNIPSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/adjustNIPSettingsRequest", ReplyAction="http://core.nip.nibss/NIPInterface/adjustNIPSettingsResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.adjustNIPSettingsResponse> adjustNIPSettingsAsync(NIBBSNIPService.adjustNIPSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/mandateadviceRequest", ReplyAction="http://core.nip.nibss/NIPInterface/mandateadviceResponse")]
        NIBBSNIPService.mandateadviceResponse mandateadvice(NIBBSNIPService.mandateadviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/mandateadviceRequest", ReplyAction="http://core.nip.nibss/NIPInterface/mandateadviceResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.mandateadviceResponse> mandateadviceAsync(NIBBSNIPService.mandateadviceRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/financialinstitutionlistRequest", ReplyAction="http://core.nip.nibss/NIPInterface/financialinstitutionlistResponse")]
        NIBBSNIPService.financialinstitutionlistResponse financialinstitutionlist(NIBBSNIPService.financialinstitutionlistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/financialinstitutionlistRequest", ReplyAction="http://core.nip.nibss/NIPInterface/financialinstitutionlistResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.financialinstitutionlistResponse> financialinstitutionlistAsync(NIBBSNIPService.financialinstitutionlistRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcResponse")]
        NIBBSNIPService.fundtransferAdvice_dcResponse fundtransferAdvice_dc(NIBBSNIPService.fundtransferAdvice_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransferAdvice_dcResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(NIBBSNIPService.fundtransferAdvice_dcRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddResponse")]
        NIBBSNIPService.fundtransferAdvice_ddResponse fundtransferAdvice_dd(NIBBSNIPService.fundtransferAdvice_ddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddRequest", ReplyAction="http://core.nip.nibss/NIPInterface/fundtransferAdvice_ddResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(NIBBSNIPService.fundtransferAdvice_ddRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsRequest", ReplyAction="http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsResponse")]
        NIBBSNIPService.privateAdjustmentOfSettingsResponse privateAdjustmentOfSettings(NIBBSNIPService.privateAdjustmentOfSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsRequest", ReplyAction="http://core.nip.nibss/NIPInterface/privateAdjustmentOfSettingsResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.privateAdjustmentOfSettingsResponse> privateAdjustmentOfSettingsAsync(NIBBSNIPService.privateAdjustmentOfSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/ftackcreditrequestRequest", ReplyAction="http://core.nip.nibss/NIPInterface/ftackcreditrequestResponse")]
        NIBBSNIPService.ftackcreditrequestResponse ftackcreditrequest(NIBBSNIPService.ftackcreditrequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://core.nip.nibss/NIPInterface/ftackcreditrequestRequest", ReplyAction="http://core.nip.nibss/NIPInterface/ftackcreditrequestResponse")]
        System.Threading.Tasks.Task<NIBBSNIPService.ftackcreditrequestResponse> ftackcreditrequestAsync(NIBBSNIPService.ftackcreditrequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nameenquirysingleitemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nameenquirysingleitem", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.nameenquirysingleitemRequestBody Body;
        
        public nameenquirysingleitemRequest()
        {
        }
        
        public nameenquirysingleitemRequest(NIBBSNIPService.nameenquirysingleitemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nameenquirysingleitemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public nameenquirysingleitemRequestBody()
        {
        }
        
        public nameenquirysingleitemRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nameenquirysingleitemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nameenquirysingleitemResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.nameenquirysingleitemResponseBody Body;
        
        public nameenquirysingleitemResponse()
        {
        }
        
        public nameenquirysingleitemResponse(NIBBSNIPService.nameenquirysingleitemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nameenquirysingleitemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public nameenquirysingleitemResponseBody()
        {
        }
        
        public nameenquirysingleitemResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_dcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_dc", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransfersingleitem_dcRequestBody Body;
        
        public fundtransfersingleitem_dcRequest()
        {
        }
        
        public fundtransfersingleitem_dcRequest(NIBBSNIPService.fundtransfersingleitem_dcRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransfersingleitem_dcRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public fundtransfersingleitem_dcRequestBody()
        {
        }
        
        public fundtransfersingleitem_dcRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_dcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_dcResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransfersingleitem_dcResponseBody Body;
        
        public fundtransfersingleitem_dcResponse()
        {
        }
        
        public fundtransfersingleitem_dcResponse(NIBBSNIPService.fundtransfersingleitem_dcResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransfersingleitem_dcResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fundtransfersingleitem_dcResponseBody()
        {
        }
        
        public fundtransfersingleitem_dcResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_ddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_dd", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransfersingleitem_ddRequestBody Body;
        
        public fundtransfersingleitem_ddRequest()
        {
        }
        
        public fundtransfersingleitem_ddRequest(NIBBSNIPService.fundtransfersingleitem_ddRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransfersingleitem_ddRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public fundtransfersingleitem_ddRequestBody()
        {
        }
        
        public fundtransfersingleitem_ddRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_ddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_ddResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransfersingleitem_ddResponseBody Body;
        
        public fundtransfersingleitem_ddResponse()
        {
        }
        
        public fundtransfersingleitem_ddResponse(NIBBSNIPService.fundtransfersingleitem_ddResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransfersingleitem_ddResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fundtransfersingleitem_ddResponseBody()
        {
        }
        
        public fundtransfersingleitem_ddResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txnstatusquerysingleitemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txnstatusquerysingleitem", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.txnstatusquerysingleitemRequestBody Body;
        
        public txnstatusquerysingleitemRequest()
        {
        }
        
        public txnstatusquerysingleitemRequest(NIBBSNIPService.txnstatusquerysingleitemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class txnstatusquerysingleitemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public txnstatusquerysingleitemRequestBody()
        {
        }
        
        public txnstatusquerysingleitemRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txnstatusquerysingleitemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txnstatusquerysingleitemResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.txnstatusquerysingleitemResponseBody Body;
        
        public txnstatusquerysingleitemResponse()
        {
        }
        
        public txnstatusquerysingleitemResponse(NIBBSNIPService.txnstatusquerysingleitemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class txnstatusquerysingleitemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public txnstatusquerysingleitemResponseBody()
        {
        }
        
        public txnstatusquerysingleitemResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class balanceenquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="balanceenquiry", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.balanceenquiryRequestBody Body;
        
        public balanceenquiryRequest()
        {
        }
        
        public balanceenquiryRequest(NIBBSNIPService.balanceenquiryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class balanceenquiryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public balanceenquiryRequestBody()
        {
        }
        
        public balanceenquiryRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class balanceenquiryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="balanceenquiryResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.balanceenquiryResponseBody Body;
        
        public balanceenquiryResponse()
        {
        }
        
        public balanceenquiryResponse(NIBBSNIPService.balanceenquiryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class balanceenquiryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public balanceenquiryResponseBody()
        {
        }
        
        public balanceenquiryResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountblock", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.amountblockRequestBody Body;
        
        public amountblockRequest()
        {
        }
        
        public amountblockRequest(NIBBSNIPService.amountblockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class amountblockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public amountblockRequestBody()
        {
        }
        
        public amountblockRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountblockResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.amountblockResponseBody Body;
        
        public amountblockResponse()
        {
        }
        
        public amountblockResponse(NIBBSNIPService.amountblockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class amountblockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public amountblockResponseBody()
        {
        }
        
        public amountblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountunblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountunblock", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.amountunblockRequestBody Body;
        
        public amountunblockRequest()
        {
        }
        
        public amountunblockRequest(NIBBSNIPService.amountunblockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class amountunblockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public amountunblockRequestBody()
        {
        }
        
        public amountunblockRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountunblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountunblockResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.amountunblockResponseBody Body;
        
        public amountunblockResponse()
        {
        }
        
        public amountunblockResponse(NIBBSNIPService.amountunblockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class amountunblockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public amountunblockResponseBody()
        {
        }
        
        public amountunblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountblock", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.accountblockRequestBody Body;
        
        public accountblockRequest()
        {
        }
        
        public accountblockRequest(NIBBSNIPService.accountblockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accountblockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public accountblockRequestBody()
        {
        }
        
        public accountblockRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountblockResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.accountblockResponseBody Body;
        
        public accountblockResponse()
        {
        }
        
        public accountblockResponse(NIBBSNIPService.accountblockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accountblockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public accountblockResponseBody()
        {
        }
        
        public accountblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountunblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountunblock", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.accountunblockRequestBody Body;
        
        public accountunblockRequest()
        {
        }
        
        public accountunblockRequest(NIBBSNIPService.accountunblockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accountunblockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public accountunblockRequestBody()
        {
        }
        
        public accountunblockRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountunblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountunblockResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.accountunblockResponseBody Body;
        
        public accountunblockResponse()
        {
        }
        
        public accountunblockResponse(NIBBSNIPService.accountunblockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accountunblockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public accountunblockResponseBody()
        {
        }
        
        public accountunblockResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adjustNIPSettingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adjustNIPSettings", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.adjustNIPSettingsRequestBody Body;
        
        public adjustNIPSettingsRequest()
        {
        }
        
        public adjustNIPSettingsRequest(NIBBSNIPService.adjustNIPSettingsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class adjustNIPSettingsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public adjustNIPSettingsRequestBody()
        {
        }
        
        public adjustNIPSettingsRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adjustNIPSettingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adjustNIPSettingsResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.adjustNIPSettingsResponseBody Body;
        
        public adjustNIPSettingsResponse()
        {
        }
        
        public adjustNIPSettingsResponse(NIBBSNIPService.adjustNIPSettingsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class adjustNIPSettingsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public adjustNIPSettingsResponseBody()
        {
        }
        
        public adjustNIPSettingsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mandateadviceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mandateadvice", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.mandateadviceRequestBody Body;
        
        public mandateadviceRequest()
        {
        }
        
        public mandateadviceRequest(NIBBSNIPService.mandateadviceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mandateadviceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public mandateadviceRequestBody()
        {
        }
        
        public mandateadviceRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mandateadviceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mandateadviceResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.mandateadviceResponseBody Body;
        
        public mandateadviceResponse()
        {
        }
        
        public mandateadviceResponse(NIBBSNIPService.mandateadviceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mandateadviceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public mandateadviceResponseBody()
        {
        }
        
        public mandateadviceResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class financialinstitutionlistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="financialinstitutionlist", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.financialinstitutionlistRequestBody Body;
        
        public financialinstitutionlistRequest()
        {
        }
        
        public financialinstitutionlistRequest(NIBBSNIPService.financialinstitutionlistRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class financialinstitutionlistRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public financialinstitutionlistRequestBody()
        {
        }
        
        public financialinstitutionlistRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class financialinstitutionlistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="financialinstitutionlistResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.financialinstitutionlistResponseBody Body;
        
        public financialinstitutionlistResponse()
        {
        }
        
        public financialinstitutionlistResponse(NIBBSNIPService.financialinstitutionlistResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class financialinstitutionlistResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public financialinstitutionlistResponseBody()
        {
        }
        
        public financialinstitutionlistResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_dcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_dc", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransferAdvice_dcRequestBody Body;
        
        public fundtransferAdvice_dcRequest()
        {
        }
        
        public fundtransferAdvice_dcRequest(NIBBSNIPService.fundtransferAdvice_dcRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransferAdvice_dcRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public fundtransferAdvice_dcRequestBody()
        {
        }
        
        public fundtransferAdvice_dcRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_dcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_dcResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransferAdvice_dcResponseBody Body;
        
        public fundtransferAdvice_dcResponse()
        {
        }
        
        public fundtransferAdvice_dcResponse(NIBBSNIPService.fundtransferAdvice_dcResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransferAdvice_dcResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fundtransferAdvice_dcResponseBody()
        {
        }
        
        public fundtransferAdvice_dcResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_ddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_dd", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransferAdvice_ddRequestBody Body;
        
        public fundtransferAdvice_ddRequest()
        {
        }
        
        public fundtransferAdvice_ddRequest(NIBBSNIPService.fundtransferAdvice_ddRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransferAdvice_ddRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public fundtransferAdvice_ddRequestBody()
        {
        }
        
        public fundtransferAdvice_ddRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_ddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_ddResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.fundtransferAdvice_ddResponseBody Body;
        
        public fundtransferAdvice_ddResponse()
        {
        }
        
        public fundtransferAdvice_ddResponse(NIBBSNIPService.fundtransferAdvice_ddResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fundtransferAdvice_ddResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fundtransferAdvice_ddResponseBody()
        {
        }
        
        public fundtransferAdvice_ddResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class privateAdjustmentOfSettingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="privateAdjustmentOfSettings", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.privateAdjustmentOfSettingsRequestBody Body;
        
        public privateAdjustmentOfSettingsRequest()
        {
        }
        
        public privateAdjustmentOfSettingsRequest(NIBBSNIPService.privateAdjustmentOfSettingsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class privateAdjustmentOfSettingsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public privateAdjustmentOfSettingsRequestBody()
        {
        }
        
        public privateAdjustmentOfSettingsRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class privateAdjustmentOfSettingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="privateAdjustmentOfSettingsResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.privateAdjustmentOfSettingsResponseBody Body;
        
        public privateAdjustmentOfSettingsResponse()
        {
        }
        
        public privateAdjustmentOfSettingsResponse(NIBBSNIPService.privateAdjustmentOfSettingsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class privateAdjustmentOfSettingsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public privateAdjustmentOfSettingsResponseBody()
        {
        }
        
        public privateAdjustmentOfSettingsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ftackcreditrequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ftackcreditrequest", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.ftackcreditrequestRequestBody Body;
        
        public ftackcreditrequestRequest()
        {
        }
        
        public ftackcreditrequestRequest(NIBBSNIPService.ftackcreditrequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ftackcreditrequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public ftackcreditrequestRequestBody()
        {
        }
        
        public ftackcreditrequestRequestBody(string request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ftackcreditrequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ftackcreditrequestResponse", Namespace="http://core.nip.nibss/", Order=0)]
        public NIBBSNIPService.ftackcreditrequestResponseBody Body;
        
        public ftackcreditrequestResponse()
        {
        }
        
        public ftackcreditrequestResponse(NIBBSNIPService.ftackcreditrequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ftackcreditrequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ftackcreditrequestResponseBody()
        {
        }
        
        public ftackcreditrequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface NIPInterfaceChannel : NIBBSNIPService.NIPInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NIPInterfaceClient : System.ServiceModel.ClientBase<NIBBSNIPService.NIPInterface>, NIBBSNIPService.NIPInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NIPInterfaceClient() : 
                base(NIPInterfaceClient.GetDefaultBinding(), NIPInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NIPInterfacePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), NIPInterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIPInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NIPInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIPInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.nameenquirysingleitemResponse NIBBSNIPService.NIPInterface.nameenquirysingleitem(NIBBSNIPService.nameenquirysingleitemRequest request)
        {
            return base.Channel.nameenquirysingleitem(request);
        }
        
        public string nameenquirysingleitem(string request)
        {
            NIBBSNIPService.nameenquirysingleitemRequest inValue = new NIBBSNIPService.nameenquirysingleitemRequest();
            inValue.Body = new NIBBSNIPService.nameenquirysingleitemRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.nameenquirysingleitemResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).nameenquirysingleitem(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.nameenquirysingleitemResponse> NIBBSNIPService.NIPInterface.nameenquirysingleitemAsync(NIBBSNIPService.nameenquirysingleitemRequest request)
        {
            return base.Channel.nameenquirysingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.nameenquirysingleitemResponse> nameenquirysingleitemAsync(string request)
        {
            NIBBSNIPService.nameenquirysingleitemRequest inValue = new NIBBSNIPService.nameenquirysingleitemRequest();
            inValue.Body = new NIBBSNIPService.nameenquirysingleitemRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).nameenquirysingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.fundtransfersingleitem_dcResponse NIBBSNIPService.NIPInterface.fundtransfersingleitem_dc(NIBBSNIPService.fundtransfersingleitem_dcRequest request)
        {
            return base.Channel.fundtransfersingleitem_dc(request);
        }
        
        public string fundtransfersingleitem_dc(string request)
        {
            NIBBSNIPService.fundtransfersingleitem_dcRequest inValue = new NIBBSNIPService.fundtransfersingleitem_dcRequest();
            inValue.Body = new NIBBSNIPService.fundtransfersingleitem_dcRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.fundtransfersingleitem_dcResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).fundtransfersingleitem_dc(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_dcResponse> NIBBSNIPService.NIPInterface.fundtransfersingleitem_dcAsync(NIBBSNIPService.fundtransfersingleitem_dcRequest request)
        {
            return base.Channel.fundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(string request)
        {
            NIBBSNIPService.fundtransfersingleitem_dcRequest inValue = new NIBBSNIPService.fundtransfersingleitem_dcRequest();
            inValue.Body = new NIBBSNIPService.fundtransfersingleitem_dcRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).fundtransfersingleitem_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.fundtransfersingleitem_ddResponse NIBBSNIPService.NIPInterface.fundtransfersingleitem_dd(NIBBSNIPService.fundtransfersingleitem_ddRequest request)
        {
            return base.Channel.fundtransfersingleitem_dd(request);
        }
        
        public string fundtransfersingleitem_dd(string request)
        {
            NIBBSNIPService.fundtransfersingleitem_ddRequest inValue = new NIBBSNIPService.fundtransfersingleitem_ddRequest();
            inValue.Body = new NIBBSNIPService.fundtransfersingleitem_ddRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.fundtransfersingleitem_ddResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).fundtransfersingleitem_dd(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_ddResponse> NIBBSNIPService.NIPInterface.fundtransfersingleitem_ddAsync(NIBBSNIPService.fundtransfersingleitem_ddRequest request)
        {
            return base.Channel.fundtransfersingleitem_ddAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(string request)
        {
            NIBBSNIPService.fundtransfersingleitem_ddRequest inValue = new NIBBSNIPService.fundtransfersingleitem_ddRequest();
            inValue.Body = new NIBBSNIPService.fundtransfersingleitem_ddRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).fundtransfersingleitem_ddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.txnstatusquerysingleitemResponse NIBBSNIPService.NIPInterface.txnstatusquerysingleitem(NIBBSNIPService.txnstatusquerysingleitemRequest request)
        {
            return base.Channel.txnstatusquerysingleitem(request);
        }
        
        public string txnstatusquerysingleitem(string request)
        {
            NIBBSNIPService.txnstatusquerysingleitemRequest inValue = new NIBBSNIPService.txnstatusquerysingleitemRequest();
            inValue.Body = new NIBBSNIPService.txnstatusquerysingleitemRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.txnstatusquerysingleitemResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).txnstatusquerysingleitem(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.txnstatusquerysingleitemResponse> NIBBSNIPService.NIPInterface.txnstatusquerysingleitemAsync(NIBBSNIPService.txnstatusquerysingleitemRequest request)
        {
            return base.Channel.txnstatusquerysingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.txnstatusquerysingleitemResponse> txnstatusquerysingleitemAsync(string request)
        {
            NIBBSNIPService.txnstatusquerysingleitemRequest inValue = new NIBBSNIPService.txnstatusquerysingleitemRequest();
            inValue.Body = new NIBBSNIPService.txnstatusquerysingleitemRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).txnstatusquerysingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.balanceenquiryResponse NIBBSNIPService.NIPInterface.balanceenquiry(NIBBSNIPService.balanceenquiryRequest request)
        {
            return base.Channel.balanceenquiry(request);
        }
        
        public string balanceenquiry(string request)
        {
            NIBBSNIPService.balanceenquiryRequest inValue = new NIBBSNIPService.balanceenquiryRequest();
            inValue.Body = new NIBBSNIPService.balanceenquiryRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.balanceenquiryResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).balanceenquiry(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.balanceenquiryResponse> NIBBSNIPService.NIPInterface.balanceenquiryAsync(NIBBSNIPService.balanceenquiryRequest request)
        {
            return base.Channel.balanceenquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.balanceenquiryResponse> balanceenquiryAsync(string request)
        {
            NIBBSNIPService.balanceenquiryRequest inValue = new NIBBSNIPService.balanceenquiryRequest();
            inValue.Body = new NIBBSNIPService.balanceenquiryRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).balanceenquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.amountblockResponse NIBBSNIPService.NIPInterface.amountblock(NIBBSNIPService.amountblockRequest request)
        {
            return base.Channel.amountblock(request);
        }
        
        public string amountblock(string request)
        {
            NIBBSNIPService.amountblockRequest inValue = new NIBBSNIPService.amountblockRequest();
            inValue.Body = new NIBBSNIPService.amountblockRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.amountblockResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).amountblock(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.amountblockResponse> NIBBSNIPService.NIPInterface.amountblockAsync(NIBBSNIPService.amountblockRequest request)
        {
            return base.Channel.amountblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.amountblockResponse> amountblockAsync(string request)
        {
            NIBBSNIPService.amountblockRequest inValue = new NIBBSNIPService.amountblockRequest();
            inValue.Body = new NIBBSNIPService.amountblockRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).amountblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.amountunblockResponse NIBBSNIPService.NIPInterface.amountunblock(NIBBSNIPService.amountunblockRequest request)
        {
            return base.Channel.amountunblock(request);
        }
        
        public string amountunblock(string request)
        {
            NIBBSNIPService.amountunblockRequest inValue = new NIBBSNIPService.amountunblockRequest();
            inValue.Body = new NIBBSNIPService.amountunblockRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.amountunblockResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).amountunblock(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.amountunblockResponse> NIBBSNIPService.NIPInterface.amountunblockAsync(NIBBSNIPService.amountunblockRequest request)
        {
            return base.Channel.amountunblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.amountunblockResponse> amountunblockAsync(string request)
        {
            NIBBSNIPService.amountunblockRequest inValue = new NIBBSNIPService.amountunblockRequest();
            inValue.Body = new NIBBSNIPService.amountunblockRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).amountunblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.accountblockResponse NIBBSNIPService.NIPInterface.accountblock(NIBBSNIPService.accountblockRequest request)
        {
            return base.Channel.accountblock(request);
        }
        
        public string accountblock(string request)
        {
            NIBBSNIPService.accountblockRequest inValue = new NIBBSNIPService.accountblockRequest();
            inValue.Body = new NIBBSNIPService.accountblockRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.accountblockResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).accountblock(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.accountblockResponse> NIBBSNIPService.NIPInterface.accountblockAsync(NIBBSNIPService.accountblockRequest request)
        {
            return base.Channel.accountblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.accountblockResponse> accountblockAsync(string request)
        {
            NIBBSNIPService.accountblockRequest inValue = new NIBBSNIPService.accountblockRequest();
            inValue.Body = new NIBBSNIPService.accountblockRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).accountblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.accountunblockResponse NIBBSNIPService.NIPInterface.accountunblock(NIBBSNIPService.accountunblockRequest request)
        {
            return base.Channel.accountunblock(request);
        }
        
        public string accountunblock(string request)
        {
            NIBBSNIPService.accountunblockRequest inValue = new NIBBSNIPService.accountunblockRequest();
            inValue.Body = new NIBBSNIPService.accountunblockRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.accountunblockResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).accountunblock(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.accountunblockResponse> NIBBSNIPService.NIPInterface.accountunblockAsync(NIBBSNIPService.accountunblockRequest request)
        {
            return base.Channel.accountunblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.accountunblockResponse> accountunblockAsync(string request)
        {
            NIBBSNIPService.accountunblockRequest inValue = new NIBBSNIPService.accountunblockRequest();
            inValue.Body = new NIBBSNIPService.accountunblockRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).accountunblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.adjustNIPSettingsResponse NIBBSNIPService.NIPInterface.adjustNIPSettings(NIBBSNIPService.adjustNIPSettingsRequest request)
        {
            return base.Channel.adjustNIPSettings(request);
        }
        
        public string adjustNIPSettings(string request)
        {
            NIBBSNIPService.adjustNIPSettingsRequest inValue = new NIBBSNIPService.adjustNIPSettingsRequest();
            inValue.Body = new NIBBSNIPService.adjustNIPSettingsRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.adjustNIPSettingsResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).adjustNIPSettings(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.adjustNIPSettingsResponse> NIBBSNIPService.NIPInterface.adjustNIPSettingsAsync(NIBBSNIPService.adjustNIPSettingsRequest request)
        {
            return base.Channel.adjustNIPSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.adjustNIPSettingsResponse> adjustNIPSettingsAsync(string request)
        {
            NIBBSNIPService.adjustNIPSettingsRequest inValue = new NIBBSNIPService.adjustNIPSettingsRequest();
            inValue.Body = new NIBBSNIPService.adjustNIPSettingsRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).adjustNIPSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.mandateadviceResponse NIBBSNIPService.NIPInterface.mandateadvice(NIBBSNIPService.mandateadviceRequest request)
        {
            return base.Channel.mandateadvice(request);
        }
        
        public string mandateadvice(string request)
        {
            NIBBSNIPService.mandateadviceRequest inValue = new NIBBSNIPService.mandateadviceRequest();
            inValue.Body = new NIBBSNIPService.mandateadviceRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.mandateadviceResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).mandateadvice(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.mandateadviceResponse> NIBBSNIPService.NIPInterface.mandateadviceAsync(NIBBSNIPService.mandateadviceRequest request)
        {
            return base.Channel.mandateadviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.mandateadviceResponse> mandateadviceAsync(string request)
        {
            NIBBSNIPService.mandateadviceRequest inValue = new NIBBSNIPService.mandateadviceRequest();
            inValue.Body = new NIBBSNIPService.mandateadviceRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).mandateadviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.financialinstitutionlistResponse NIBBSNIPService.NIPInterface.financialinstitutionlist(NIBBSNIPService.financialinstitutionlistRequest request)
        {
            return base.Channel.financialinstitutionlist(request);
        }
        
        public string financialinstitutionlist(string request)
        {
            NIBBSNIPService.financialinstitutionlistRequest inValue = new NIBBSNIPService.financialinstitutionlistRequest();
            inValue.Body = new NIBBSNIPService.financialinstitutionlistRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.financialinstitutionlistResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).financialinstitutionlist(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.financialinstitutionlistResponse> NIBBSNIPService.NIPInterface.financialinstitutionlistAsync(NIBBSNIPService.financialinstitutionlistRequest request)
        {
            return base.Channel.financialinstitutionlistAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.financialinstitutionlistResponse> financialinstitutionlistAsync(string request)
        {
            NIBBSNIPService.financialinstitutionlistRequest inValue = new NIBBSNIPService.financialinstitutionlistRequest();
            inValue.Body = new NIBBSNIPService.financialinstitutionlistRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).financialinstitutionlistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.fundtransferAdvice_dcResponse NIBBSNIPService.NIPInterface.fundtransferAdvice_dc(NIBBSNIPService.fundtransferAdvice_dcRequest request)
        {
            return base.Channel.fundtransferAdvice_dc(request);
        }
        
        public string fundtransferAdvice_dc(string request)
        {
            NIBBSNIPService.fundtransferAdvice_dcRequest inValue = new NIBBSNIPService.fundtransferAdvice_dcRequest();
            inValue.Body = new NIBBSNIPService.fundtransferAdvice_dcRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.fundtransferAdvice_dcResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).fundtransferAdvice_dc(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_dcResponse> NIBBSNIPService.NIPInterface.fundtransferAdvice_dcAsync(NIBBSNIPService.fundtransferAdvice_dcRequest request)
        {
            return base.Channel.fundtransferAdvice_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(string request)
        {
            NIBBSNIPService.fundtransferAdvice_dcRequest inValue = new NIBBSNIPService.fundtransferAdvice_dcRequest();
            inValue.Body = new NIBBSNIPService.fundtransferAdvice_dcRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).fundtransferAdvice_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.fundtransferAdvice_ddResponse NIBBSNIPService.NIPInterface.fundtransferAdvice_dd(NIBBSNIPService.fundtransferAdvice_ddRequest request)
        {
            return base.Channel.fundtransferAdvice_dd(request);
        }
        
        public string fundtransferAdvice_dd(string request)
        {
            NIBBSNIPService.fundtransferAdvice_ddRequest inValue = new NIBBSNIPService.fundtransferAdvice_ddRequest();
            inValue.Body = new NIBBSNIPService.fundtransferAdvice_ddRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.fundtransferAdvice_ddResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).fundtransferAdvice_dd(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_ddResponse> NIBBSNIPService.NIPInterface.fundtransferAdvice_ddAsync(NIBBSNIPService.fundtransferAdvice_ddRequest request)
        {
            return base.Channel.fundtransferAdvice_ddAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(string request)
        {
            NIBBSNIPService.fundtransferAdvice_ddRequest inValue = new NIBBSNIPService.fundtransferAdvice_ddRequest();
            inValue.Body = new NIBBSNIPService.fundtransferAdvice_ddRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).fundtransferAdvice_ddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.privateAdjustmentOfSettingsResponse NIBBSNIPService.NIPInterface.privateAdjustmentOfSettings(NIBBSNIPService.privateAdjustmentOfSettingsRequest request)
        {
            return base.Channel.privateAdjustmentOfSettings(request);
        }
        
        public string privateAdjustmentOfSettings(string request)
        {
            NIBBSNIPService.privateAdjustmentOfSettingsRequest inValue = new NIBBSNIPService.privateAdjustmentOfSettingsRequest();
            inValue.Body = new NIBBSNIPService.privateAdjustmentOfSettingsRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.privateAdjustmentOfSettingsResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).privateAdjustmentOfSettings(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.privateAdjustmentOfSettingsResponse> NIBBSNIPService.NIPInterface.privateAdjustmentOfSettingsAsync(NIBBSNIPService.privateAdjustmentOfSettingsRequest request)
        {
            return base.Channel.privateAdjustmentOfSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.privateAdjustmentOfSettingsResponse> privateAdjustmentOfSettingsAsync(string request)
        {
            NIBBSNIPService.privateAdjustmentOfSettingsRequest inValue = new NIBBSNIPService.privateAdjustmentOfSettingsRequest();
            inValue.Body = new NIBBSNIPService.privateAdjustmentOfSettingsRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).privateAdjustmentOfSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIBBSNIPService.ftackcreditrequestResponse NIBBSNIPService.NIPInterface.ftackcreditrequest(NIBBSNIPService.ftackcreditrequestRequest request)
        {
            return base.Channel.ftackcreditrequest(request);
        }
        
        public string ftackcreditrequest(string request)
        {
            NIBBSNIPService.ftackcreditrequestRequest inValue = new NIBBSNIPService.ftackcreditrequestRequest();
            inValue.Body = new NIBBSNIPService.ftackcreditrequestRequestBody();
            inValue.Body.request = request;
            NIBBSNIPService.ftackcreditrequestResponse retVal = ((NIBBSNIPService.NIPInterface)(this)).ftackcreditrequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NIBBSNIPService.ftackcreditrequestResponse> NIBBSNIPService.NIPInterface.ftackcreditrequestAsync(NIBBSNIPService.ftackcreditrequestRequest request)
        {
            return base.Channel.ftackcreditrequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<NIBBSNIPService.ftackcreditrequestResponse> ftackcreditrequestAsync(string request)
        {
            NIBBSNIPService.ftackcreditrequestRequest inValue = new NIBBSNIPService.ftackcreditrequestRequest();
            inValue.Body = new NIBBSNIPService.ftackcreditrequestRequestBody();
            inValue.Body.request = request;
            return ((NIBBSNIPService.NIPInterface)(this)).ftackcreditrequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NIPInterfacePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NIPInterfacePort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.234.10.204:86/NIPWS/NIPInterface");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NIPInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.NIPInterfacePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NIPInterfaceClient.GetEndpointAddress(EndpointConfiguration.NIPInterfacePort);
        }
        
        public enum EndpointConfiguration
        {
            
            NIPInterfacePort,
        }
    }
}
