apiVersion: v1
kind: Service
metadata:
  name: nipoutboundapi
  labels: 
    app: nipoutboundapi
spec:
  selector:
    app: nipoutboundapi
  ports:
  - name: http
    port: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nipoutboundapi
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nipoutboundapi
  template:
    metadata:
      labels:
        app: nipoutboundapi
        version: v1
    spec:
      containers:
      - name: nipoutboundapi
        image: "tcoeregistry2.azurecr.io/sterling-bank-nipoutbound-api:#{ Build.BuildId }#"
        ports:
        - containerPort: 80 