//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTeller
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTeller.nfpSoap")]
    public interface nfpSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NIBBS", ReplyAction="*")]
        System.Threading.Tasks.Task<VTeller.NIBBSResponse> NIBBSAsync(VTeller.NIBBSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NIBBSInward", ReplyAction="*")]
        System.Threading.Tasks.Task<VTeller.NIBBSInwardResponse> NIBBSInwardAsync(VTeller.NIBBSInwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NIBBSWithSenderBvn", ReplyAction="*")]
        System.Threading.Tasks.Task<VTeller.NIBBSWithSenderBvnResponse> NIBBSWithSenderBvnAsync(VTeller.NIBBSWithSenderBvnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NIBBSInwardWithSenderBvn", ReplyAction="*")]
        System.Threading.Tasks.Task<VTeller.NIBBSInwardWithSenderBvnResponse> NIBBSInwardWithSenderBvnAsync(VTeller.NIBBSInwardWithSenderBvnRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBS", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSRequestBody Body;
        
        public NIBBSRequest()
        {
        }
        
        public NIBBSRequest(VTeller.NIBBSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SessionID;
        
        public NIBBSRequestBody()
        {
        }
        
        public NIBBSRequestBody(string xml, string trnxType, string SessionID)
        {
            this.xml = xml;
            this.trnxType = trnxType;
            this.SessionID = SessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSResponse", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSResponseBody Body;
        
        public NIBBSResponse()
        {
        }
        
        public NIBBSResponse(VTeller.NIBBSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIBBSResult;
        
        public NIBBSResponseBody()
        {
        }
        
        public NIBBSResponseBody(string NIBBSResult)
        {
            this.NIBBSResult = NIBBSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSInwardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSInward", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSInwardRequestBody Body;
        
        public NIBBSInwardRequest()
        {
        }
        
        public NIBBSInwardRequest(VTeller.NIBBSInwardRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSInwardRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        public NIBBSInwardRequestBody()
        {
        }
        
        public NIBBSInwardRequestBody(string xml, string trnxType)
        {
            this.xml = xml;
            this.trnxType = trnxType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSInwardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSInwardResponse", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSInwardResponseBody Body;
        
        public NIBBSInwardResponse()
        {
        }
        
        public NIBBSInwardResponse(VTeller.NIBBSInwardResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSInwardResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIBBSInwardResult;
        
        public NIBBSInwardResponseBody()
        {
        }
        
        public NIBBSInwardResponseBody(string NIBBSInwardResult)
        {
            this.NIBBSInwardResult = NIBBSInwardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSWithSenderBvnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSWithSenderBvn", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSWithSenderBvnRequestBody Body;
        
        public NIBBSWithSenderBvnRequest()
        {
        }
        
        public NIBBSWithSenderBvnRequest(VTeller.NIBBSWithSenderBvnRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSWithSenderBvnRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bvnOfTransactionInitiator;
        
        public NIBBSWithSenderBvnRequestBody()
        {
        }
        
        public NIBBSWithSenderBvnRequestBody(string xml, string trnxType, string bvnOfTransactionInitiator)
        {
            this.xml = xml;
            this.trnxType = trnxType;
            this.bvnOfTransactionInitiator = bvnOfTransactionInitiator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSWithSenderBvnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSWithSenderBvnResponse", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSWithSenderBvnResponseBody Body;
        
        public NIBBSWithSenderBvnResponse()
        {
        }
        
        public NIBBSWithSenderBvnResponse(VTeller.NIBBSWithSenderBvnResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSWithSenderBvnResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIBBSWithSenderBvnResult;
        
        public NIBBSWithSenderBvnResponseBody()
        {
        }
        
        public NIBBSWithSenderBvnResponseBody(string NIBBSWithSenderBvnResult)
        {
            this.NIBBSWithSenderBvnResult = NIBBSWithSenderBvnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSInwardWithSenderBvnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSInwardWithSenderBvn", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSInwardWithSenderBvnRequestBody Body;
        
        public NIBBSInwardWithSenderBvnRequest()
        {
        }
        
        public NIBBSInwardWithSenderBvnRequest(VTeller.NIBBSInwardWithSenderBvnRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSInwardWithSenderBvnRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bvnOfTransactionInitiator;
        
        public NIBBSInwardWithSenderBvnRequestBody()
        {
        }
        
        public NIBBSInwardWithSenderBvnRequestBody(string xml, string trnxType, string bvnOfTransactionInitiator)
        {
            this.xml = xml;
            this.trnxType = trnxType;
            this.bvnOfTransactionInitiator = bvnOfTransactionInitiator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBBSInwardWithSenderBvnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBBSInwardWithSenderBvnResponse", Namespace="http://tempuri.org/", Order=0)]
        public VTeller.NIBBSInwardWithSenderBvnResponseBody Body;
        
        public NIBBSInwardWithSenderBvnResponse()
        {
        }
        
        public NIBBSInwardWithSenderBvnResponse(VTeller.NIBBSInwardWithSenderBvnResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBBSInwardWithSenderBvnResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIBBSInwardWithSenderBvnResult;
        
        public NIBBSInwardWithSenderBvnResponseBody()
        {
        }
        
        public NIBBSInwardWithSenderBvnResponseBody(string NIBBSInwardWithSenderBvnResult)
        {
            this.NIBBSInwardWithSenderBvnResult = NIBBSInwardWithSenderBvnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface nfpSoapChannel : VTeller.nfpSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class nfpSoapClient : System.ServiceModel.ClientBase<VTeller.nfpSoap>, VTeller.nfpSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public nfpSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(nfpSoapClient.GetBindingForEndpoint(endpointConfiguration), nfpSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfpSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(nfpSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfpSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(nfpSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VTeller.NIBBSResponse> VTeller.nfpSoap.NIBBSAsync(VTeller.NIBBSRequest request)
        {
            return base.Channel.NIBBSAsync(request);
        }
        
        public System.Threading.Tasks.Task<VTeller.NIBBSResponse> NIBBSAsync(string xml, string trnxType, string SessionID)
        {
            VTeller.NIBBSRequest inValue = new VTeller.NIBBSRequest();
            inValue.Body = new VTeller.NIBBSRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.SessionID = SessionID;
            return ((VTeller.nfpSoap)(this)).NIBBSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VTeller.NIBBSInwardResponse> VTeller.nfpSoap.NIBBSInwardAsync(VTeller.NIBBSInwardRequest request)
        {
            return base.Channel.NIBBSInwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<VTeller.NIBBSInwardResponse> NIBBSInwardAsync(string xml, string trnxType)
        {
            VTeller.NIBBSInwardRequest inValue = new VTeller.NIBBSInwardRequest();
            inValue.Body = new VTeller.NIBBSInwardRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            return ((VTeller.nfpSoap)(this)).NIBBSInwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VTeller.NIBBSWithSenderBvnResponse> VTeller.nfpSoap.NIBBSWithSenderBvnAsync(VTeller.NIBBSWithSenderBvnRequest request)
        {
            return base.Channel.NIBBSWithSenderBvnAsync(request);
        }
        
        public System.Threading.Tasks.Task<VTeller.NIBBSWithSenderBvnResponse> NIBBSWithSenderBvnAsync(string xml, string trnxType, string bvnOfTransactionInitiator)
        {
            VTeller.NIBBSWithSenderBvnRequest inValue = new VTeller.NIBBSWithSenderBvnRequest();
            inValue.Body = new VTeller.NIBBSWithSenderBvnRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.bvnOfTransactionInitiator = bvnOfTransactionInitiator;
            return ((VTeller.nfpSoap)(this)).NIBBSWithSenderBvnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VTeller.NIBBSInwardWithSenderBvnResponse> VTeller.nfpSoap.NIBBSInwardWithSenderBvnAsync(VTeller.NIBBSInwardWithSenderBvnRequest request)
        {
            return base.Channel.NIBBSInwardWithSenderBvnAsync(request);
        }
        
        public System.Threading.Tasks.Task<VTeller.NIBBSInwardWithSenderBvnResponse> NIBBSInwardWithSenderBvnAsync(string xml, string trnxType, string bvnOfTransactionInitiator)
        {
            VTeller.NIBBSInwardWithSenderBvnRequest inValue = new VTeller.NIBBSInwardWithSenderBvnRequest();
            inValue.Body = new VTeller.NIBBSInwardWithSenderBvnRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.bvnOfTransactionInitiator = bvnOfTransactionInitiator;
            return ((VTeller.nfpSoap)(this)).NIBBSInwardWithSenderBvnAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfpSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.nfpSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfpSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.41.102:814/nfp.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.nfpSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.41.102:814/nfp.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            nfpSoap,
            
            nfpSoap12,
        }
    }
}
