//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameEnquiry
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameEnquiry.NewIBSSoap")]
    public interface NewIBSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTxt", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.getTxtResponse> getTxtAsync(NameEnquiry.getTxtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NameEnquiry", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.NameEnquiryResponse> NameEnquiryAsync(NameEnquiry.NameEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DebitandSendtoNIBSS", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSSResponse> DebitandSendtoNIBSSAsync(NameEnquiry.DebitandSendtoNIBSSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DebitandSendtoNIBSST24", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSST24Response> DebitandSendtoNIBSST24Async(NameEnquiry.DebitandSendtoNIBSST24Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NIBSSReversal", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.NIBSSReversalResponse> NIBSSReversalAsync(NameEnquiry.NIBSSReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/requeryTrnx", ReplyAction="*")]
        System.Threading.Tasks.Task<NameEnquiry.requeryTrnxResponse> requeryTrnxAsync(NameEnquiry.requeryTrnxRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTxtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTxt", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.getTxtRequestBody Body;
        
        public getTxtRequest()
        {
        }
        
        public getTxtRequest(NameEnquiry.getTxtRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTxtRequestBody
    {
        
        public getTxtRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTxtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTxtResponse", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.getTxtResponseBody Body;
        
        public getTxtResponse()
        {
        }
        
        public getTxtResponse(NameEnquiry.getTxtResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTxtResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTxtResult;
        
        public getTxtResponseBody()
        {
        }
        
        public getTxtResponseBody(string getTxtResult)
        {
            this.getTxtResult = getTxtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameEnquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameEnquiry", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.NameEnquiryRequestBody Body;
        
        public NameEnquiryRequest()
        {
        }
        
        public NameEnquiryRequest(NameEnquiry.NameEnquiryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameEnquiryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DestinationBankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ChannelCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccountNumber;
        
        public NameEnquiryRequestBody()
        {
        }
        
        public NameEnquiryRequestBody(string SessionID, string DestinationBankCode, string ChannelCode, string AccountNumber)
        {
            this.SessionID = SessionID;
            this.DestinationBankCode = DestinationBankCode;
            this.ChannelCode = ChannelCode;
            this.AccountNumber = AccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameEnquiryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameEnquiryResponse", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.NameEnquiryResponseBody Body;
        
        public NameEnquiryResponse()
        {
        }
        
        public NameEnquiryResponse(NameEnquiry.NameEnquiryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NameEnquiryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameEnquiryResult;
        
        public NameEnquiryResponseBody()
        {
        }
        
        public NameEnquiryResponseBody(string NameEnquiryResult)
        {
            this.NameEnquiryResult = NameEnquiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitandSendtoNIBSSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebitandSendtoNIBSS", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.DebitandSendtoNIBSSRequestBody Body;
        
        public DebitandSendtoNIBSSRequest()
        {
        }
        
        public DebitandSendtoNIBSSRequest(NameEnquiry.DebitandSendtoNIBSSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitandSendtoNIBSSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bracodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusnumval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string curcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ledcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subacctval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string amt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string orignatorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DestinationBankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ChannelCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string paymentRef;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string cusshowname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int Appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Referenceidval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string BeneficiaryBankVerificationNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string BeneficiaryKYCLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string OriginatorAccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string OriginatorBankVerificationNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string OriginatorKYCLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string TransactionLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string NameEnquiryRef;
        
        public DebitandSendtoNIBSSRequestBody()
        {
        }
        
        public DebitandSendtoNIBSSRequestBody(
                    string sessionid, 
                    string bracodeval, 
                    string cusnumval, 
                    string curcodeval, 
                    string ledcodeval, 
                    string subacctval, 
                    string amt, 
                    string fee, 
                    string orignatorName, 
                    string DestinationBankCode, 
                    string ChannelCode, 
                    string AccountName, 
                    string AccountNumber, 
                    string paymentRef, 
                    string cusshowname, 
                    int Appid, 
                    string Referenceidval, 
                    string BeneficiaryBankVerificationNumber, 
                    string BeneficiaryKYCLevel, 
                    string OriginatorAccountNumber, 
                    string OriginatorBankVerificationNumber, 
                    string OriginatorKYCLevel, 
                    string TransactionLocation, 
                    string NameEnquiryRef)
        {
            this.sessionid = sessionid;
            this.bracodeval = bracodeval;
            this.cusnumval = cusnumval;
            this.curcodeval = curcodeval;
            this.ledcodeval = ledcodeval;
            this.subacctval = subacctval;
            this.amt = amt;
            this.fee = fee;
            this.orignatorName = orignatorName;
            this.DestinationBankCode = DestinationBankCode;
            this.ChannelCode = ChannelCode;
            this.AccountName = AccountName;
            this.AccountNumber = AccountNumber;
            this.paymentRef = paymentRef;
            this.cusshowname = cusshowname;
            this.Appid = Appid;
            this.Referenceidval = Referenceidval;
            this.BeneficiaryBankVerificationNumber = BeneficiaryBankVerificationNumber;
            this.BeneficiaryKYCLevel = BeneficiaryKYCLevel;
            this.OriginatorAccountNumber = OriginatorAccountNumber;
            this.OriginatorBankVerificationNumber = OriginatorBankVerificationNumber;
            this.OriginatorKYCLevel = OriginatorKYCLevel;
            this.TransactionLocation = TransactionLocation;
            this.NameEnquiryRef = NameEnquiryRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitandSendtoNIBSSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebitandSendtoNIBSSResponse", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.DebitandSendtoNIBSSResponseBody Body;
        
        public DebitandSendtoNIBSSResponse()
        {
        }
        
        public DebitandSendtoNIBSSResponse(NameEnquiry.DebitandSendtoNIBSSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitandSendtoNIBSSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DebitandSendtoNIBSSResult;
        
        public DebitandSendtoNIBSSResponseBody()
        {
        }
        
        public DebitandSendtoNIBSSResponseBody(string DebitandSendtoNIBSSResult)
        {
            this.DebitandSendtoNIBSSResult = DebitandSendtoNIBSSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitandSendtoNIBSST24Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebitandSendtoNIBSST24", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.DebitandSendtoNIBSST24RequestBody Body;
        
        public DebitandSendtoNIBSST24Request()
        {
        }
        
        public DebitandSendtoNIBSST24Request(NameEnquiry.DebitandSendtoNIBSST24RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitandSendtoNIBSST24RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bracodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusnumval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string curcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ledcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subacctval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string amt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string orignatorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DestinationBankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ChannelCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string paymentRef;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string cusshowname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int Appid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Referenceidval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string BeneficiaryBankVerificationNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string BeneficiaryKYCLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string OriginatorAccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string OriginatorBankVerificationNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string OriginatorKYCLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string TransactionLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string NameEnquiryRef;
        
        public DebitandSendtoNIBSST24RequestBody()
        {
        }
        
        public DebitandSendtoNIBSST24RequestBody(
                    string sessionid, 
                    string bracodeval, 
                    string cusnumval, 
                    string curcodeval, 
                    string ledcodeval, 
                    string subacctval, 
                    string amt, 
                    string fee, 
                    string orignatorName, 
                    string DestinationBankCode, 
                    string ChannelCode, 
                    string AccountName, 
                    string AccountNumber, 
                    string paymentRef, 
                    string cusshowname, 
                    int Appid, 
                    string Referenceidval, 
                    string BeneficiaryBankVerificationNumber, 
                    string BeneficiaryKYCLevel, 
                    string OriginatorAccountNumber, 
                    string OriginatorBankVerificationNumber, 
                    string OriginatorKYCLevel, 
                    string TransactionLocation, 
                    string NameEnquiryRef)
        {
            this.sessionid = sessionid;
            this.bracodeval = bracodeval;
            this.cusnumval = cusnumval;
            this.curcodeval = curcodeval;
            this.ledcodeval = ledcodeval;
            this.subacctval = subacctval;
            this.amt = amt;
            this.fee = fee;
            this.orignatorName = orignatorName;
            this.DestinationBankCode = DestinationBankCode;
            this.ChannelCode = ChannelCode;
            this.AccountName = AccountName;
            this.AccountNumber = AccountNumber;
            this.paymentRef = paymentRef;
            this.cusshowname = cusshowname;
            this.Appid = Appid;
            this.Referenceidval = Referenceidval;
            this.BeneficiaryBankVerificationNumber = BeneficiaryBankVerificationNumber;
            this.BeneficiaryKYCLevel = BeneficiaryKYCLevel;
            this.OriginatorAccountNumber = OriginatorAccountNumber;
            this.OriginatorBankVerificationNumber = OriginatorBankVerificationNumber;
            this.OriginatorKYCLevel = OriginatorKYCLevel;
            this.TransactionLocation = TransactionLocation;
            this.NameEnquiryRef = NameEnquiryRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitandSendtoNIBSST24Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebitandSendtoNIBSST24Response", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.DebitandSendtoNIBSST24ResponseBody Body;
        
        public DebitandSendtoNIBSST24Response()
        {
        }
        
        public DebitandSendtoNIBSST24Response(NameEnquiry.DebitandSendtoNIBSST24ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitandSendtoNIBSST24ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DebitandSendtoNIBSST24Result;
        
        public DebitandSendtoNIBSST24ResponseBody()
        {
        }
        
        public DebitandSendtoNIBSST24ResponseBody(string DebitandSendtoNIBSST24Result)
        {
            this.DebitandSendtoNIBSST24Result = DebitandSendtoNIBSST24Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBSSReversalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBSSReversal", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.NIBSSReversalRequestBody Body;
        
        public NIBSSReversalRequest()
        {
        }
        
        public NIBSSReversalRequest(NameEnquiry.NIBSSReversalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBSSReversalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bracodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusnumval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string curcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ledcodeval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subacctval;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string amt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string orignatorName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DestinationBankCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ChannelCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string AccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Narration;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string cusshowname;
        
        public NIBSSReversalRequestBody()
        {
        }
        
        public NIBSSReversalRequestBody(string sessionid, string bracodeval, string cusnumval, string curcodeval, string ledcodeval, string subacctval, string amt, string fee, string orignatorName, string DestinationBankCode, string ChannelCode, string AccountName, string AccountNumber, string Narration, string cusshowname)
        {
            this.sessionid = sessionid;
            this.bracodeval = bracodeval;
            this.cusnumval = cusnumval;
            this.curcodeval = curcodeval;
            this.ledcodeval = ledcodeval;
            this.subacctval = subacctval;
            this.amt = amt;
            this.fee = fee;
            this.orignatorName = orignatorName;
            this.DestinationBankCode = DestinationBankCode;
            this.ChannelCode = ChannelCode;
            this.AccountName = AccountName;
            this.AccountNumber = AccountNumber;
            this.Narration = Narration;
            this.cusshowname = cusshowname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NIBSSReversalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NIBSSReversalResponse", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.NIBSSReversalResponseBody Body;
        
        public NIBSSReversalResponse()
        {
        }
        
        public NIBSSReversalResponse(NameEnquiry.NIBSSReversalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NIBSSReversalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NIBSSReversalResult;
        
        public NIBSSReversalResponseBody()
        {
        }
        
        public NIBSSReversalResponseBody(string NIBSSReversalResult)
        {
            this.NIBSSReversalResult = NIBSSReversalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requeryTrnxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requeryTrnx", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.requeryTrnxRequestBody Body;
        
        public requeryTrnxRequest()
        {
        }
        
        public requeryTrnxRequest(NameEnquiry.requeryTrnxRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class requeryTrnxRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionNE;
        
        public requeryTrnxRequestBody()
        {
        }
        
        public requeryTrnxRequestBody(string sessionNE)
        {
            this.sessionNE = sessionNE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requeryTrnxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requeryTrnxResponse", Namespace="http://tempuri.org/", Order=0)]
        public NameEnquiry.requeryTrnxResponseBody Body;
        
        public requeryTrnxResponse()
        {
        }
        
        public requeryTrnxResponse(NameEnquiry.requeryTrnxResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class requeryTrnxResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requeryTrnxResult;
        
        public requeryTrnxResponseBody()
        {
        }
        
        public requeryTrnxResponseBody(string requeryTrnxResult)
        {
            this.requeryTrnxResult = requeryTrnxResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface NewIBSSoapChannel : NameEnquiry.NewIBSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NewIBSSoapClient : System.ServiceModel.ClientBase<NameEnquiry.NewIBSSoap>, NameEnquiry.NewIBSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NewIBSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NewIBSSoapClient.GetBindingForEndpoint(endpointConfiguration), NewIBSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewIBSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NewIBSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewIBSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NewIBSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewIBSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.getTxtResponse> NameEnquiry.NewIBSSoap.getTxtAsync(NameEnquiry.getTxtRequest request)
        {
            return base.Channel.getTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.getTxtResponse> getTxtAsync()
        {
            NameEnquiry.getTxtRequest inValue = new NameEnquiry.getTxtRequest();
            inValue.Body = new NameEnquiry.getTxtRequestBody();
            return ((NameEnquiry.NewIBSSoap)(this)).getTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.NameEnquiryResponse> NameEnquiry.NewIBSSoap.NameEnquiryAsync(NameEnquiry.NameEnquiryRequest request)
        {
            return base.Channel.NameEnquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.NameEnquiryResponse> NameEnquiryAsync(string SessionID, string DestinationBankCode, string ChannelCode, string AccountNumber)
        {
            NameEnquiry.NameEnquiryRequest inValue = new NameEnquiry.NameEnquiryRequest();
            inValue.Body = new NameEnquiry.NameEnquiryRequestBody();
            inValue.Body.SessionID = SessionID;
            inValue.Body.DestinationBankCode = DestinationBankCode;
            inValue.Body.ChannelCode = ChannelCode;
            inValue.Body.AccountNumber = AccountNumber;
            return ((NameEnquiry.NewIBSSoap)(this)).NameEnquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSSResponse> NameEnquiry.NewIBSSoap.DebitandSendtoNIBSSAsync(NameEnquiry.DebitandSendtoNIBSSRequest request)
        {
            return base.Channel.DebitandSendtoNIBSSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSSResponse> DebitandSendtoNIBSSAsync(
                    string sessionid, 
                    string bracodeval, 
                    string cusnumval, 
                    string curcodeval, 
                    string ledcodeval, 
                    string subacctval, 
                    string amt, 
                    string fee, 
                    string orignatorName, 
                    string DestinationBankCode, 
                    string ChannelCode, 
                    string AccountName, 
                    string AccountNumber, 
                    string paymentRef, 
                    string cusshowname, 
                    int Appid, 
                    string Referenceidval, 
                    string BeneficiaryBankVerificationNumber, 
                    string BeneficiaryKYCLevel, 
                    string OriginatorAccountNumber, 
                    string OriginatorBankVerificationNumber, 
                    string OriginatorKYCLevel, 
                    string TransactionLocation, 
                    string NameEnquiryRef)
        {
            NameEnquiry.DebitandSendtoNIBSSRequest inValue = new NameEnquiry.DebitandSendtoNIBSSRequest();
            inValue.Body = new NameEnquiry.DebitandSendtoNIBSSRequestBody();
            inValue.Body.sessionid = sessionid;
            inValue.Body.bracodeval = bracodeval;
            inValue.Body.cusnumval = cusnumval;
            inValue.Body.curcodeval = curcodeval;
            inValue.Body.ledcodeval = ledcodeval;
            inValue.Body.subacctval = subacctval;
            inValue.Body.amt = amt;
            inValue.Body.fee = fee;
            inValue.Body.orignatorName = orignatorName;
            inValue.Body.DestinationBankCode = DestinationBankCode;
            inValue.Body.ChannelCode = ChannelCode;
            inValue.Body.AccountName = AccountName;
            inValue.Body.AccountNumber = AccountNumber;
            inValue.Body.paymentRef = paymentRef;
            inValue.Body.cusshowname = cusshowname;
            inValue.Body.Appid = Appid;
            inValue.Body.Referenceidval = Referenceidval;
            inValue.Body.BeneficiaryBankVerificationNumber = BeneficiaryBankVerificationNumber;
            inValue.Body.BeneficiaryKYCLevel = BeneficiaryKYCLevel;
            inValue.Body.OriginatorAccountNumber = OriginatorAccountNumber;
            inValue.Body.OriginatorBankVerificationNumber = OriginatorBankVerificationNumber;
            inValue.Body.OriginatorKYCLevel = OriginatorKYCLevel;
            inValue.Body.TransactionLocation = TransactionLocation;
            inValue.Body.NameEnquiryRef = NameEnquiryRef;
            return ((NameEnquiry.NewIBSSoap)(this)).DebitandSendtoNIBSSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSST24Response> NameEnquiry.NewIBSSoap.DebitandSendtoNIBSST24Async(NameEnquiry.DebitandSendtoNIBSST24Request request)
        {
            return base.Channel.DebitandSendtoNIBSST24Async(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.DebitandSendtoNIBSST24Response> DebitandSendtoNIBSST24Async(
                    string sessionid, 
                    string bracodeval, 
                    string cusnumval, 
                    string curcodeval, 
                    string ledcodeval, 
                    string subacctval, 
                    string amt, 
                    string fee, 
                    string orignatorName, 
                    string DestinationBankCode, 
                    string ChannelCode, 
                    string AccountName, 
                    string AccountNumber, 
                    string paymentRef, 
                    string cusshowname, 
                    int Appid, 
                    string Referenceidval, 
                    string BeneficiaryBankVerificationNumber, 
                    string BeneficiaryKYCLevel, 
                    string OriginatorAccountNumber, 
                    string OriginatorBankVerificationNumber, 
                    string OriginatorKYCLevel, 
                    string TransactionLocation, 
                    string NameEnquiryRef)
        {
            NameEnquiry.DebitandSendtoNIBSST24Request inValue = new NameEnquiry.DebitandSendtoNIBSST24Request();
            inValue.Body = new NameEnquiry.DebitandSendtoNIBSST24RequestBody();
            inValue.Body.sessionid = sessionid;
            inValue.Body.bracodeval = bracodeval;
            inValue.Body.cusnumval = cusnumval;
            inValue.Body.curcodeval = curcodeval;
            inValue.Body.ledcodeval = ledcodeval;
            inValue.Body.subacctval = subacctval;
            inValue.Body.amt = amt;
            inValue.Body.fee = fee;
            inValue.Body.orignatorName = orignatorName;
            inValue.Body.DestinationBankCode = DestinationBankCode;
            inValue.Body.ChannelCode = ChannelCode;
            inValue.Body.AccountName = AccountName;
            inValue.Body.AccountNumber = AccountNumber;
            inValue.Body.paymentRef = paymentRef;
            inValue.Body.cusshowname = cusshowname;
            inValue.Body.Appid = Appid;
            inValue.Body.Referenceidval = Referenceidval;
            inValue.Body.BeneficiaryBankVerificationNumber = BeneficiaryBankVerificationNumber;
            inValue.Body.BeneficiaryKYCLevel = BeneficiaryKYCLevel;
            inValue.Body.OriginatorAccountNumber = OriginatorAccountNumber;
            inValue.Body.OriginatorBankVerificationNumber = OriginatorBankVerificationNumber;
            inValue.Body.OriginatorKYCLevel = OriginatorKYCLevel;
            inValue.Body.TransactionLocation = TransactionLocation;
            inValue.Body.NameEnquiryRef = NameEnquiryRef;
            return ((NameEnquiry.NewIBSSoap)(this)).DebitandSendtoNIBSST24Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.NIBSSReversalResponse> NameEnquiry.NewIBSSoap.NIBSSReversalAsync(NameEnquiry.NIBSSReversalRequest request)
        {
            return base.Channel.NIBSSReversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.NIBSSReversalResponse> NIBSSReversalAsync(string sessionid, string bracodeval, string cusnumval, string curcodeval, string ledcodeval, string subacctval, string amt, string fee, string orignatorName, string DestinationBankCode, string ChannelCode, string AccountName, string AccountNumber, string Narration, string cusshowname)
        {
            NameEnquiry.NIBSSReversalRequest inValue = new NameEnquiry.NIBSSReversalRequest();
            inValue.Body = new NameEnquiry.NIBSSReversalRequestBody();
            inValue.Body.sessionid = sessionid;
            inValue.Body.bracodeval = bracodeval;
            inValue.Body.cusnumval = cusnumval;
            inValue.Body.curcodeval = curcodeval;
            inValue.Body.ledcodeval = ledcodeval;
            inValue.Body.subacctval = subacctval;
            inValue.Body.amt = amt;
            inValue.Body.fee = fee;
            inValue.Body.orignatorName = orignatorName;
            inValue.Body.DestinationBankCode = DestinationBankCode;
            inValue.Body.ChannelCode = ChannelCode;
            inValue.Body.AccountName = AccountName;
            inValue.Body.AccountNumber = AccountNumber;
            inValue.Body.Narration = Narration;
            inValue.Body.cusshowname = cusshowname;
            return ((NameEnquiry.NewIBSSoap)(this)).NIBSSReversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NameEnquiry.requeryTrnxResponse> NameEnquiry.NewIBSSoap.requeryTrnxAsync(NameEnquiry.requeryTrnxRequest request)
        {
            return base.Channel.requeryTrnxAsync(request);
        }
        
        public System.Threading.Tasks.Task<NameEnquiry.requeryTrnxResponse> requeryTrnxAsync(string sessionNE)
        {
            NameEnquiry.requeryTrnxRequest inValue = new NameEnquiry.requeryTrnxRequest();
            inValue.Body = new NameEnquiry.requeryTrnxRequestBody();
            inValue.Body.sessionNE = sessionNE;
            return ((NameEnquiry.NewIBSSoap)(this)).requeryTrnxAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NewIBSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NewIBSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NewIBSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.41.102:8084/NewIBS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NewIBSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.41.102:8084/NewIBS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NewIBSSoap,
            
            NewIBSSoap12,
        }
    }
}
